[sources.in_logs]
type = "systemd_journal_gatewayd"
endpoint = "2a04:9dc0:0:108:6801:d6ff:fe59:eae1"

[sinks.out_logs]
type = "console"
inputs = ["in_logs"]
target = "stdout"
    [sinks.out_logs.encoding]
    codec = "json"