# [sources.in_logs_5j7vn]
# type = "sns_canister"
# endpoint = "https://3e3x2-xyaaa-aaaaq-aaalq-cai.raw.ic0.app"
# data_dir = "logs"

# [sinks.out_logs]
# type = "file"
# inputs = ["in_logs_*"]
# compression = "none"
# path = "logs/logs.log"
#     [sinks.out_logs.encoding]
#     codec = "json"

[sinks.my_sink_id]
type = "blackhole"
inputs = [ "*-transform" ]