# Component Features - Linux
#
# Validates that each component feature compiles
#
# Runs on:
#  - scheduled UTC midnight Tues-Sat
#  - on PR comment (see comment-trigger.yml)
#  - on demand from github actions UI

name: Component Features - Linux

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    # At midnight UTC Tue-Sat
    - cron: '0 0 * * 2-6'

jobs:
  check-component-features:
    # use free tier on schedule and 8 core to expedite results on demand invocation
    runs-on: ${{ github.event_name == 'schedule' && 'ubuntu-latest' || 'ubuntu-20.04-8core' }}
    if: github.event_name == 'issue_comment' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    steps:
      - name: (PR comment) Get PR branch
        if: github.event_name == 'issue_comment'
        uses: xt0rted/pull-request-comment-branch@d97294d304604fa98a2600a6e2f916a84b596dc7 # v2
        id: comment-branch

      - name: (PR comment) Set latest commit status as pending
        if: github.event_name == 'issue_comment'
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          context: Component Features - Linux
          status: pending

      - name: (PR comment) Checkout PR branch
        if: github.event_name == 'issue_comment'
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: Checkout branch
        if: github.event_name != 'issue_comment'
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make check-component-features

      - name: (PR comment) Set latest commit status as ${{ job.status }}
        if: always() && github.event_name == 'issue_comment'
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          context: Component Features - Linux
          status: ${{ job.status }}
