name: Miscellaneous - Linux

on:
  workflow_call:

jobs:
  test-misc:
    runs-on: ubuntu-20.04-4core
    timeout-minutes: 60
    env:
      CARGO_INCREMENTAL: 0
    steps:
      - name: (PR comment) Get PR branch
        if: ${{ github.event_name == 'issue_comment' }}
        uses: xt0rted/pull-request-comment-branch@d97294d304604fa98a2600a6e2f916a84b596dc7 # v2
        id: comment-branch

      - name: (PR comment) Set latest commit status as pending
        if: ${{ github.event_name == 'issue_comment' }}
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          context: Miscellaneous - Linux
          status: pending

      - name: (PR comment) Checkout PR branch
        if: ${{ github.event_name == 'issue_comment' }}
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: Checkout branch
        if: ${{ github.event_name != 'issue_comment' }}
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        name: Cache Cargo registry + index
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make test-behavior
      - run: make check-examples
      - run: make test-docs

      - name: (PR comment) Set latest commit status as ${{ job.status }}
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        if: always() && github.event_name == 'issue_comment'
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          context: Miscellaneous - Linux
          status: ${{ job.status }}
