name: Protobuf Compatibility

on:
  pull_request:
    paths:
        - "proto/**"
        - "lib/vector-core/proto/**"
  merge_group:
    types: [checks_requested]

concurrency:
    # `github.ref` is unique for MQ runs and PRs
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  validate-protos:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Run `git checkout`
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      # Install the `buf` CLI
      - uses: bufbuild/buf-setup-action@59e8ac0671772e5ffef08a41b3aec11d39fc1165 # v1.33.0
      # Perform breaking change detection against the `master` branch
      - uses: bufbuild/buf-breaking-action@c57b3d842a5c3f3b454756ef65305a50a587c5ba # v1.1.4
        with:
          against: "https://github.com/vectordotdev/vector.git#branch=master"
